{
 "title": "Cardano P2P Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Negotiated duplex connections (including DuplexState connections)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_duplexConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Hot peers (active connections)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_hot",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Remote peers that have the local peer as hot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_inbound_governor_hot",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Negotiated unidirectional connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_unidirectionalConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Warm peers (established but not active connection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_warm",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Remote peers that have the local peer as warm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_inbound_governor_warm",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_incomingConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cold peers (known but without established connection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_cold",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Network usefulness factor (tm): ratio of blocks served in last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_served_block_latest_count_int[1h])/rate(cardano_node_metrics_blockNum_int[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Outbound connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_outgoingConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within one second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks adopted within one second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockadoption_cdfOne_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Connections relevant for pruning",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_prunableConns",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within three seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfThree",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks adopted within three seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockadoption_cdfThree_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Ratio of late (>5s delay) blocks in the last hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockfetchclient_lateblocks[1h])/rate(cardano_node_metrics_blockNum_int[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks arrived within five seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfFive",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks adopted within five seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockadoption_cdfFive_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block propagation delay (seconds) - last 15 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.5,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-a-.*\"}[15m]))",
     "legendFormat": "Europe (Frankfurt) P50"
    },
    {
     "expr": "avg(quantile_over_time(0.5,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-b-.*\"}[15m]))",
     "legendFormat": "US East (Ohio) P50"
    },
    {
     "expr": "avg(quantile_over_time(0.5,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-c-.*\"}[15m]))",
     "legendFormat": "Asia Pacific (Singapore) P50"
    },
    {
     "expr": "avg(quantile_over_time(0.5,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-d-.*\"}[15m]))",
     "legendFormat": "Europe (London) P50"
    },
    {
     "expr": "avg(quantile_over_time(0.5,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-e-.*\"}[15m]))",
     "legendFormat": "US West (N. California) P50"
    },
    {
     "expr": "avg(quantile_over_time(0.5,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-f-.*\"}[15m]))",
     "legendFormat": "Asia Pacific (Tokyo) P50"
    },
    {
     "expr": "avg(quantile_over_time(0.95,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-a-.*\"}[15m]))",
     "legendFormat": "Europe (Frankfurt) P95"
    },
    {
     "expr": "avg(quantile_over_time(0.95,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-b-.*\"}[15m]))",
     "legendFormat": "US East (Ohio) P95"
    },
    {
     "expr": "avg(quantile_over_time(0.95,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-c-.*\"}[15m]))",
     "legendFormat": "Asia Pacific (Singapore) P95"
    },
    {
     "expr": "avg(quantile_over_time(0.95,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-d-.*\"}[15m]))",
     "legendFormat": "Europe (London) P95"
    },
    {
     "expr": "avg(quantile_over_time(0.95,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-e-.*\"}[15m]))",
     "legendFormat": "US West (N. California) P95"
    },
    {
     "expr": "avg(quantile_over_time(0.95,cardano_node_metrics_blockfetchclient_blockdelay_s{alias=~\"rel-f-.*\"}[15m]))",
     "legendFormat": "Asia Pacific (Tokyo) P95"
    }
   ]
  },
  {
   "title": "Block internal processing delay (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockadoption_delay_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block adoption total delay (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.5, cardano_node_metrics_blockadoption_forgeDelay_real[15m]))",
     "legendFormat": "P50 last 15m"
    },
    {
     "expr": "avg(quantile_over_time(0.95, cardano_node_metrics_blockadoption_forgeDelay_real[1h]))",
     "legendFormat": "P95 last hour"
    },
    {
     "expr": "avg(quantile_over_time(0.95, cardano_node_metrics_blockadoption_forgeDelay_real[6h:30s]))",
     "legendFormat": "P95 last 6 hours"
    }
   ]
  }
 ]
}