{
 "title": "Cardano: Chain Sync Debug",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "new node blocks/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_ChainDB_blockNum_int[1m]) * 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "proxy blocks/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_byron_proxy_ChainDB_blockNum_int[5m]) * 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "legacy node blocks/min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(cardano_total_main_blocks[5m]) * 60)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "all the nodes blocks/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_ChainDB_blockNum_int[1m]) * 60",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(cardano_total_main_blocks[5m]) * 60",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(cardano_byron_proxy_ChainDB_blockNum_int[5m]) * 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "rts bytes allocated per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(rts_gc_bytes_allocated[1m])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "gc bytes copied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(rts_gc_bytes_copied[1m])", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "ms spent in gc, per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(rts_gc_cpu_ms[1m]) < 2000", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "gc's per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "rate(rts_gc_num_gcs[1m])", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "clock offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "node_timex_offset_seconds", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "gc current bytes used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rts_gc_current_bytes_used", "legendFormat": "{{alias}}" }
   ]
  }
 ]
}