{
 "title": "Explorer Python API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Explorer Python API Hit Rate (Hits per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Address API Hits/hr" }
   ],
   "targets": [
    {
     "expr": "rate(address_summary_hist_count[1h])*3600"
    }
   ]
  },
  {
   "title": "Explorer Python API Avg Response Time (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "2XX Avg Response (s)" }
   ],
   "targets": [
    {
     "expr": "address_summary_hist_sum / address_summary_hist_count"
    }
   ]
  },
  {
   "title": "Explorer Python API Heatmap, 2m Rolling Window, Opacity View",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(address_summary_hist_bucket{status=\"200\"}[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Explorer Python API Heatmap, 2m Rolling Window, Spectrum View",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(address_summary_hist_bucket{status=\"200\"}[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Explorer Python API Total Hit Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Address API Hits" }
   ],
   "targets": [
    { "expr": "address_summary_hist_count" }
   ]
  },
  {
   "title": "Python Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Python Block Height" }
   ],
   "targets": [
    { "expr": "block_height" }
   ]
  }
 ]
}