{
 "title": "Kernel versions",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "release",
    "query": "label_values(node_uname_info,release)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "All  Nodes At Set Kernel Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "ver",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_uname_info{release=\"$release\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "node count per kernel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_uname_info) by (release)"
    }
   ]
  },
  {
   "title": "Deployment Kernel Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds)"
    }
   ]
  }
 ]
}